project:
  type: website
  output-dir: docs

website:
  title: "DS4I: Kenneth Ssekimpi"
  navbar:
    left:
      - href: https://github.com/digable-dissenter/
        text: Home
      - href: Assignment 1.qmd
        text: Assignment 1
      - href: Assignment 2.qmd
        text: Assignment 2

format:
  html:
    theme: cosmo
    css: index.css
    toc: true
